### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by karniv00l** [electron/node-abi#100]
Latest released version (`v2.19.3`) incorrectly returns `ABI  85` for `Electron 12.0.0-beta.1` which leads to issues when using `prebuild` (https://github.com/prebuild/prebuild/issues/273).

**Comment by m4heshd** [comment]
Yup. In fact a huge issue.


![image](https://user-images.githubusercontent.com/6711514/108602712-76948e00-73c9-11eb-9b1e-aa0db117336f.png)

**Comment by dperetti** [comment]
12.0.0 is out...

**Comment by kryops** [comment]
If you use yarn, you can use a resolution in your `package.json` as a workaround that points to the latest commit:

```
"resolutions": {
  "node-abi": "https://github.com/lgeiger/node-abi.git#d7a3f00c93cb16b5f4fbb3ae8c106e798cc52042"
}
```
