### ISSUE TITLE
Electron version 18.0.3

### ISSUE THREAD

**Issue by danielehrhardt** [electron/node-abi#120]
Could not detect abi for version 18.0.3 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

**Comment by seb-mtl** [comment]
Is there any update on this?

**Comment by seb-mtl** [comment]
You might have a module that has a dependency to an old version of `prebuild-install`. Installing your own version to `7.1.0` fixed the issue. Solution:

`npm i -D prebuild-install@7.1.0`
