### ISSUE TITLE
Release to update semver with vulnerability fix

### ISSUE THREAD

**Issue by Shepard** [electron/node-abi#143]
node-abi is a transitive dependency for a library I use. It depends on semver for which a vulnerability was recently fixed, which `npm audit` reports: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

It seems dependabot already updated the semver dependency in this project to include the fixes. Could you please release a new version with this dependency update? Thanks!

**Comment by MarshallOfSound** [comment]
@Shepard The published version of `node-abi` already has a dependency on semver in a range that is acceptable.  You can fix this in your app / dependency tree without us releasing a new version.
