### ISSUE TITLE
No entry for Electron 33.0.2

### ISSUE THREAD

**Issue by cseickel** [electron/node-abi#189]
Or 33.0.1, 33.0.0. What triggers a new release to be packaged? Is is on a certain schedule and I just need to wait x days after a new Electron version is released?

https://github.com/electron/electron/releases/tag/v33.0.2

**Comment by VerteDinde** [comment]
Hey @cseickel, this was a bug in our headers upload - it should now be fixed. Let me know if you have any more trouble!

**Comment by cseickel** [comment]
Don't we need a new release of this library to make this change effective?
