### ISSUE TITLE
move to the prebuild org

### ISSUE THREAD

**Issue by mafintosh** [electron/node-abi#58]
If you are interested it might be good to move this to the prebuild org so we can all help out more easily :)

**Comment by lgeiger** [comment]
Sure, I'd be happy to move it or give access to more people. Though I need to find time to migrate CI and autopublishing too.

**Comment by MarshallOfSound** [comment]
Might be a bit self-centered here but as long as I retain the ability to push out new Electron ABI versions I'm 👍

**Comment by mafintosh** [comment]
@MarshallOfSound We can add you to the org if that works for you?

**Comment by MarshallOfSound** [comment]
@mafintosh Yup that works for me 👍

**Comment by mafintosh** [comment]
friendly bump on this :)

**Comment by MarshallOfSound** [comment]
This issue is super old but looks like it's moved over to the `electron` side of the house now.  Happy to add y'all as having write access here @mafintosh just let me know and I can get our bots to give you write access

**Comment by mafintosh** [comment]
Write access sounds good, we depend heavily on this. Other than that just happy to see it get some care :)
