### ISSUE TITLE
node-abi is very late with support for new versions of Electron

### ISSUE THREAD

**Issue by CezaryKulakowski** [electron/node-abi#88]
When new version of Electron is created it takes a lot of time before it's supported by node-abi. In current situation there is no support for Electron 10 so it's not possible to rebuild native modules for application which uses Electron 10 as module electron-rebuild uses node-abi to get information about abi version for the given version of Electron. Would it be possible to add support for new version of Electron as soon as it is created (as nightly version)? I could create pull requests with required changes when new version of Electron is created in the future.

**Comment by Armaldio** [comment]
It could be inspired by https://github.com/Armaldio/modules-abi
Would be happy to merge my work

**Comment by GreatBoy** [comment]
9.0.4 or 9.0.5

**Comment by Sergey-Churilin** [comment]
Got such error:  Error: Could not detect abi for version 9.1.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

**Comment by mcthulhu** [comment]
I'm getting the same error, which seems to prevent my Electron project from running: 

An unhandled error has occurred inside Forge:
Could not detect abi for version 9.1.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

**Comment by NoahAndrews** [comment]
@malept It looks to me like the commit that added support for Electron 10 failed to trigger an automated patch release. Maybe because [CI failed](https://travis-ci.org/github/lgeiger/node-abi/builds/721183322)?

**Comment by malept** [comment]
Despite the testsuite failure in `node-abi`, Electron 10 support is included and working in `node-abi` 2.19.1. The `electron-rebuild` testsuite is using Electron 10 and passes.

**Comment by rwwagner90** [comment]
I'm getting `Could not detect abi for version 13.0.0-nightly.20210202 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron` for most nightly versions. Is there a way to have this package auto update daily to pull in nightlies?

**Comment by MarshallOfSound** [comment]
This should be substantially quicker nowadays, the auto-updater runs every hour and the publish should happen instantly
